language: python
python:
  - '3.5'
  - '3.6'
  - 3.7-dev
  - nightly
install:
  - pip install .
  - pip install -r test_requirements.txt
script:
  - nosetests
#deploy:
#  provider: pypi
#  user:
#    secure: Tq84YVi2QINfE5hRXrkddgUF+GNqCmjA6BLGXIJb/+GrIK4v3BtiJwRl5jdD9lAnIXe81yNlh6V1Njt9hTo8nBbAYILegnh43SAfrwCDf7Jl2OHH8bjYloiLWFvvQ7gq6b/PI37lymPJSadPHeQk1ryDzRPCIxSotZKANoSOsc8+wnQUneLJItteoJ+/DmdsrHC0cCOaR1V6iAcWBmemdvlnPQWExN4Jxqe91ytqFa4/Rr/0C35P9BpqZKY2/zhqA2s+YLPrI4TFChLJniIH89mZkvwaA0iJaKnMhR7cWXyhLVznMONa6K8H/f3Keza/g0JZHneFnhE4ABjQ4bZqdFdjYeCkG10MVkCPb9cwOnxooy89TpylrszJQpxs94dy3E7XY+lmTqWhcuIXA7rohK+lQ2Zl86gEsV06q8gJJb+zvxfCMHbv3maEAVgj1GNu0xZvCXaQFbH2w44BBGaYjJdfPU4ao2hVHoaAXqB2JMT3uKU/AB/BmfSojVsTp+S65XLaNDVVvy7NfGP8vIyoXUW0SneJp2F9U2lV7YQvU3crjLYpH4W1smtjYaeaif1KZq4RdWpULsw9p05KHJbAlLGpGe8vvP/AAfzNktxGv0rMkA8nKGYzSXOkQ65y2TCFV2gB2VyUNAn7hp3mED9cnK4IXDgSg0rjlkMR+5AcCMI=
#  password:
#    secure: RgFKLzbhfQDdJS/pgswIQ8s/rBfQPEcFatCI8lYOmpDC1prf/BwATIENXqAZtE0c/gkTMlp3saOPPpwAHWpXAp2VhOJLcQNHgbNoVgO9ArH/cWbhjpgR+iNqYsRoPOQax20OqKPQxCRElEaXzTqPqtfrzcX3gJyVZuGgZptig7FpQw2t09peduUuS3ljqXYc6dfPmcZJek9c/ChDyBE/daDXtbOUOPubVi2E62TvaXPkYLtZmT6J1KNMnurk8QCgHC72J9AkCSH8266LnRwK5s8zGEHku5AASw/fQ0NvO8NvjxVKh55rnjPheJ5j5nMkR54L1oJP0OMA5oCWiOhBIUmYJyKD6o42eh+V7Ap45jTOBdnyrSbBSo/id3RSXfzfVzjlhazx+XtvWVE1Ne2x0PrURpIyRP+nfH8s3pBqbn91tfY+7svpvRUeNzVJeSZfYCb+6W+cpGzFGm0KaHEByE63ctxPaG8D1GAUQP7vPmV6g2UDJLHPG1eS1txAXiKq4drohkhzzIBqIlLw4XSCFJ/ytuAFImtzWrwBKmQO4KwnBk+wCR0bGVWIE/8FZTGYrX3jfQE5pUq20+2yzrLB6O15/iXZOVLRoDiF504BCJdaPq0neIiAFpDIL9Du3SFSsJTXT5JRPs7Ba8GHUzopDBOWq5H4vAR00T+ZiOHT+/A=
#  distributions: sdist bdist_wheel
#  skip_cleanup: true
#  skip_existing: true
#  on:
#    branch: master
#    tags: true
#    python: 3.6
